echo off
color 0a
cls
title [ ! ] USING 32 THREADS
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
start %CD%\sys\ATK_L_RUN.bat
